image: nixos/nix

before_script:
  - nix-channel --add https://nixos.org/channels/nixpkgs-unstable
  - nix-channel --update
  - nix-shell --pure

deps:
  stage: build
  script:
  - mix local.hex --force
  - mix deps.get

test:
  stage: test
  script: mix test

pages:
  stage: deploy
  script:
  - mix docs
  - mv doc public
  artifacts:
    paths:
    - public
  only:
  - master
