image: nixos/nix

before_script:
  - nix-channel --add https://nixos.org/channels/nixpkgs-unstable
  - nix-channel --update

test:
  stage: test
  script: nix-shell --run 'mix test'

pages:
  stage: deploy
  script: nix-shell --run 'mix docs --output public'
  artifacts:
    paths:
    - public
  only:
  - master
